### ISSUE TITLE
Inverse Power Feedback

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Vehicles#44]
Use this issue to discuss your opinions and give feedback about Inverse Power and its settings.
This is not a complaint form, give reasoning and support your opinion. 
Remember, Inverse power effects EVERY CAR ON THE SERVER, so please do not base it off of a single car or a single track.

**Comment by mPrism** [comment]
I was a huge fan of the previous Inverse Power, mainly because it closed the gap between the faster cars and the slower cars. 

Fast cars were more prone to slip and drift which gave an opportunity to the ‘slow cars’ to catch up. 

The Evo 8 (only evo I drove) felt fairly balanced against other cars when the wiggle boost wasn’t used. 

Front Wheel Drive cars were much harder to use since the extra power to the front wheels made it snap straight, but it could be worked around with better lines. 

I believe that the tweaked inverse power would be better for new players getting into the server and would give a “easier to play/hard to master” feel to it.

**Comment by TheAussie** [comment]
Since this isn't really talked about im closing it.
